import SwiftUI

struct SettingsView: View {
    @AppStorage("settings.uiLanguage") private var uiLanguageRaw = UILanguage.system.rawValue

    var body: some View {
        NavigationStack {
            Form {
                appearanceSection
                generationSection
                aboutSection
            }
            .scrollContentBackground(.hidden)
            .background(Color.slydeeCream)
            .navigationTitle("Settings")
        }
    }

    private var appearanceSection: some View {
        Section("Appearance") {
            Picker("App language", selection: $uiLanguageRaw) {
                ForEach(UILanguage.allCases) { lang in
                    Text(lang.displayName).tag(lang.rawValue)
                }
            }
        }
    }

    private var generationSection: some View {
        Section {
            LabeledContent("AI engine", value: "Google Gemini")
        } header: {
            Text("Generation")
        } footer: {
            Text("Presentations and research are generated by Google Gemini — no setup or API keys required. Works for Arabic, English, and Mixed.")
        }
    }

    private var aboutSection: some View {
        Section("About") {
            LabeledContent("Version", value: AppSettings.appVersion)
            LabeledContent("Made by", value: "Mohammed Raad (Hamoudi)")
            Text("Slydee — beautiful slides in seconds.")
                .font(SlydeeFont.body(FontSize.caption))
                .foregroundStyle(Color.slydeeInkMuted)
        }
    }
}

#Preview {
    SettingsView()
}
